import getQueryClient from '@/app/lib/getQueryClient';
import { dehydrate } from '@tanstack/react-query';
import graphqlRequestClient from '@/app/lib/graphqlRequestClient';
import { AllLandingPageDocument } from '@/app/lib/__generated/sanity.autogenerated';
import Modules from '@/app/src/components/Modules';
import { ReactQueryHydrate } from '@/app/src/components/shared/ReactQueryHydrate';

export default async function LandingPage({ params: { slug } }: { params: { slug: string } }) {
    const queryClient = getQueryClient();
    await queryClient.prefetchQuery(['allLandingPage'], () =>
        graphqlRequestClient.request(AllLandingPageDocument, { slug }),
    );
    const dehydratedState = dehydrate(queryClient, {
        shouldDehydrateQuery: () => true,
    });

    return (
        <ReactQueryHydrate state={dehydratedState}>
            <Modules slug={slug} />
        </ReactQueryHydrate>
    );
}
